### ISSUE TITLE
How to spawn buildings on an empire's home planet

### ISSUE THREAD

**Issue by aaronfranke** [DJDaemonix/stellaris-api#1]
The building reference seems to contain information on how to add custom buildings, but not how to spawn them. I would like to spawn vanilla buildings on an empire's home planet based on a custom civic which I've already created. Also, if possible, I would like to do the same with districts.

This is more of a call for help, but it would also be nice to update this API reference with this info.

**Comment by DJDaemonix** [comment]
Hello @aaronfranke,

I didn't update this API ref, as i'm using the one internal to PDX for game & mod development ; Hence, why this repo is horribly outdated.

If you really show interest in this, i'd be happy to help you out in setting up VS Code to point towards your /common folder. It might be easier than keeping this reference updated every once in every year or so ^^

With regards,
DJ Daemonix

**Comment by aaronfranke** [comment]
Point towards? Can the /common folder be treated as a language server in VS Code?

Feel free to post a link to a guide for how to do that, but if you don't want to update this repo I guess I'll close this since I already received help on Reddit: https://old.reddit.com/r/StellarisMods/comments/gt02w3/how_do_i_spawn_buildings_on_the_home_planet/

**Comment by DJDaemonix** [comment]
For VS Code's Clausewitz scripting support, might i suggest you look into a VS Code extension called "CWTools". IMHO the best language support for Stellaris & HOI4.

Pointing that extension to you Stellaris base game folder, it will automatically recognize all relevant symbols for autocompletion. Quite a handy piece of software.
